name: Artifact Merge

on: push

env:
  ARTIFACT_NAME: Myartifact
  
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
